version: '3'
services:
  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: 'rnd_C92YjAM5tX4vknjS9GOYaJszSMP4'
      SECRET: 'replace-with-random-value'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      DB_CLIENT: 'pg'
      DB_HOST: 'dpg-cmi0u4mn7f5s73a09blg-a'
      DB_PORT: '5432'
      DB_DATABASE: 'directus_h6fs'
      DB_USER: 'directus_h6fs_user'
      DB_PASSWORD: 'aN5olGAexAftbYrvI01hlhDTmAsgpSh8'
